# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib {
  /home/andrew/projects/EE178/final_project/final_project.srcs/sources_1/imports/software/software.v
  /home/andrew/projects/EE178/final_project/final_project.srcs/sources_1/imports/software/kcpsm6.v
  /home/andrew/projects/EE178/final_project/final_project.srcs/sources_1/new/final_project.v
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/andrew/projects/EE178/final_project/final_project.cache/wt [current_project]
set_property parent.project_dir /home/andrew/projects/EE178/final_project [current_project]
synth_design -top final_project -part xc7a100tcsg324-1
write_checkpoint final_project.dcp
report_utilization -file final_project_utilization_synth.rpt -pb final_project_utilization_synth.pb
