# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/andrew/vivadoprojects/lab6/lab6.srcs/sources_1/ip/phonemes_1/phonemes.xci
# IP: The module: 'phonemes' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andrew/vivadoprojects/lab6/lab6.srcs/sources_1/ip/phonemes_1/phonemes_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'phonemes'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/andrew/vivadoprojects/lab6/lab6.srcs/sources_1/ip/phonemes_1/phonemes.xci
# IP: The module: 'phonemes' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/andrew/vivadoprojects/lab6/lab6.srcs/sources_1/ip/phonemes_1/phonemes_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'phonemes'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
