# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog -library xil_defaultlib {
  /home/andrew/projects/EE178/alarmclock/alarmclock.srcs/sources_1/new/display.v
  /home/andrew/projects/EE178/alarmclock/alarmclock.srcs/sources_1/new/controller.v
  /home/andrew/projects/EE178/alarmclock/alarmclock.srcs/sources_1/new/clock.v
  /home/andrew/projects/EE178/alarmclock/alarmclock.srcs/sources_1/new/main_source.v
}
read_xdc /home/andrew/projects/EE178/alarmclock/alarmclock.srcs/constrs_1/new/alarmclock.xdc
set_property used_in_implementation false [get_files /home/andrew/projects/EE178/alarmclock/alarmclock.srcs/constrs_1/new/alarmclock.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/andrew/projects/EE178/alarmclock/alarmclock.cache/wt [current_project]
set_property parent.project_dir /home/andrew/projects/EE178/alarmclock [current_project]
synth_design -top main_source -part xc7a100tcsg324-1
write_checkpoint main_source.dcp
report_utilization -file main_source_utilization_synth.rpt -pb main_source_utilization_synth.pb
