# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
add_files /home/andrew/vivadoprojects/lab6/lab6.srcs/sources_1/imports/phonemes/phonemes.coe
add_files /home/andrew/vivadoprojects/lab6/files/phonemes/phonemes.coe
add_files /home/andrew/vivadoprojects/lab6/lab6.runs/phonemes_synth_1/phonemes.dcp
set_property used_in_implementation false [get_files /home/andrew/vivadoprojects/lab6/lab6.runs/phonemes_synth_1/phonemes.dcp]
set_property use_blackbox_stub false [get_files /home/andrew/vivadoprojects/lab6/lab6.runs/phonemes_synth_1/phonemes.dcp]
read_verilog {
  /home/andrew/vivadoprojects/lab6/lab6.srcs/sources_1/imports/files/narrator.v
  /home/andrew/vivadoprojects/lab6/lab6.srcs/sources_1/imports/files/chatter.v
  /home/andrew/vivadoprojects/lab6/lab6.srcs/sources_1/imports/files/fsm.v
  /home/andrew/vivadoprojects/lab6/lab6.srcs/sources_1/imports/files/dac.v
  /home/andrew/vivadoprojects/lab6/lab6.srcs/sources_1/ip/phonemes_1/phonemes_stub.v
}
read_xdc /home/andrew/vivadoprojects/lab6/lab6.srcs/constrs_1/imports/files/narrator.xdc
set_property used_in_implementation false [get_files /home/andrew/vivadoprojects/lab6/lab6.srcs/constrs_1/imports/files/narrator.xdc]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/andrew/vivadoprojects/lab6/lab6.data/wt [current_project]
set_property parent.project_dir /home/andrew/vivadoprojects/lab6 [current_project]
synth_design -top narrator -part xc7a100tcsg324-1
write_checkpoint narrator.dcp
report_utilization -file narrator_utilization_synth.rpt -pb narrator_utilization_synth.pb
