set_property SRC_FILE_INFO {cfile:/home/andrew/vivadoprojects/lab6/lab6.srcs/constrs_1/imports/files/narrator.xdc rfile:../../../lab6.srcs/constrs_1/imports/files/narrator.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A11 [get_ports speaker]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D12 [get_ports vcc]
