# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
read_verilog {
  /home/andrew/vivadoprojects/lab7/software/software.v
  /home/andrew/vivadoprojects/lab7/lab7.srcs/sources_1/imports/lab7files/kcpsm6.v
  /home/andrew/vivadoprojects/lab7/lab7.srcs/sources_1/imports/lab7files/tutorial.v
}
read_xdc /home/andrew/vivadoprojects/lab7/lab7.srcs/constrs_1/imports/lab7files/tutorial.xdc
set_property used_in_implementation false [get_files /home/andrew/vivadoprojects/lab7/lab7.srcs/constrs_1/imports/lab7files/tutorial.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/andrew/vivadoprojects/lab7/lab7.data/wt [current_project]
set_property parent.project_dir /home/andrew/vivadoprojects/lab7 [current_project]
synth_design -top tutorial -part xc7a100tcsg324-1
write_checkpoint tutorial.dcp
report_utilization -file tutorial_utilization_synth.rpt -pb tutorial_utilization_synth.pb
